name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: "Check this to skip pushing the Docker image"
        default: false 

jobs:
  lint-and-test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Test
        run: npm test

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-action-school:${{ github.sha }} .

      - name: Push Docker Image to Docker Hub
        if: ${{ inputs['dry-run'] == 'false' }}  
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-action-school:${{ github.sha }}
